name: turing
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.3.1
  riverpod_annotation: any
  http: ^1.3.0
  http_interceptor: ^2.0.0
  logger: ^2.0.2
  json_annotation: ^4.8.0
  kakao_flutter_sdk_user: ^1.9.6
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  build_runner: ^2.4.11
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/config/.env
  

